package org.pmiops.workbench.mail;

// used by MailServiceImpl to make template substitutions
public enum EmailSubstitutionField {
  ACTION("ACTION"),
  ALL_OF_US("ALL_OF_US"),
  BADGE_URL("BADGE_URL"),
  BILLING_ACCOUNT_DETAILS("BILLING_ACCOUNT_DETAILS"),
  BULLET_1("BULLET_1"),
  BULLET_2("BULLET_2"),
  BULLET_3("BULLET_3"),
  CREDIT_BALANCE("CREDIT_BALANCE"),
  CT_STEPS("CT_STEPS"),
  DISK_COST_PER_MONTH("DISK_COST_PER_MONTH"),
  DISK_CREATION_DATE("DISK_CREATION_DATE"),
  DISK_CREATOR_USERNAME("DISK_CREATOR_USERNAME"),
  DISK_DELETE_INSTRUCTION("DISK_DELETE_INSTRUCTION"),
  DISK_SIZE("DISK_SIZE"),
  DISK_STATUS("DISK_STATUS"),
  DISK_UNUSED_DAYS("DISK_UNUSED_DAYS"),
  EGRESS_REMEDIATION_DESCRIPTION("EGRESS_REMEDIATION_DESCRIPTION"),
  ENVIRONMENT_TYPE("ENVIRONMENT_TYPE"),
  EXPIRATION_DATE("EXPIRATION_DATE"),
  FIRST_NAME("FIRST_NAME"),
  FROM_EMAIL("FROM_EMAIL"),
  HEADER_IMG("HEADER_IMG"),
  INITIAL_CREDITS_RESOLUTION("INITIAL_CREDITS_RESOLUTION"),
  INSTITUTION_NAME("INSTITUTION_NAME"),
  INSTRUCTIONS("INSTRUCTIONS"),
  LAST_NAME("LAST_NAME"),
  LOCKING_REASON("LOCKING_REASON"),
  NIH_FUNDED("NIH_FUNDED"),
  PASSWORD("PASSWORD"),
  RAB_SUPPORT_EMAIL("RAB_SUPPORT_EMAIL"),
  REGISTRATION_IMG("REGISTRATION_IMG"),
  REMAINING_DAYS("REMAINING_DAYS"),
  RT_STEPS("RT_STEPS"),
  SURVEY_LINK("SURVEY_LINK"),
  TIER("TIER"),
  TOS_HREF("TOS_HREF"),
  URL("URL"),
  USED_CREDITS("USED_CREDITS"),
  USERNAME("USERNAME"),
  USER_CONTACT_EMAIL("USER_CONTACT_EMAIL"),
  USER_PHONE("USER_PHONE"),
  WORKSPACE_NAME("WORKSPACE_NAME"),
  WORKSPACE_NAMESPACE("WORKSPACE_NAMESPACE"),
  WORKSPACE_URL("WORKSPACE_URL");

  private final String value;

  EmailSubstitutionField(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }
}
