= Prerequisites

Install Node.js and npm:
https://g3doc.corp.google.com/third_party/javascript/node_modules/g3doc/installing-node.md#goobuntu

Install the Angular command-line tool (optional?):

 sudo npm install -g @angular/cli

= Run for Development

== First Time

Install project deps:

 npm install

Direct your editor to write swap files outside the source tree, so Webpack
does not reload when they're updated.
https://github.com/angular/angular-cli/issues/4593[Example for vim].

== Every Time

From the project root:

 ng serve

= Source Code

All the interesting code is under `src/app/`.

`*.component.ts` are UI components, controlling various widgets; they have associated `*.component.html` and/or `*.component.css` for their templated DOM and style. Angular scopes CSS to its associated component.

`*.service.ts` provide data. In a real app, these would probably wrap REST APIs.

`*.module.ts` set up glue to stick the app together: routing of URLs to different views, installation of the various components/services for use in other places.

= Deploy

Build static source files, created under `dist/`:

 ng build --prod

Deploy to AppEngine:

https://jaykhimani.blogspot.com/2016/10/deploying-angular-2-app-with-angular.html

= References

Tutorial w/ TypeScript: https://angular.io/docs/ts/latest/tutorial/
