export const START_REQUEST = 'START_REQUEST';
export const CANCEL_REQUEST = 'CANCEL_REQUEST';
export const CLEANUP_REQUEST = 'CLEANUP_REQUEST';

export const BEGIN_CRITERIA_REQUEST = 'BEGIN_CRITERIA_REQUEST';
export const LOAD_CRITERIA_RESULTS = 'LOAD_CRITERIA_RESULTS';

export const BEGIN_COUNT_REQUEST = 'BEGIN_COUNT_REQUEST';
export const LOAD_COUNT_RESULTS = 'LOAD_COUNT_RESULTS';

export const INIT_SEARCH_GROUP = 'INIT_SEARCH_GROUP';
export const INIT_GROUP_ITEM = 'INIT_GROUP_ITEM';
export const SELECT_CRITERIA = 'SELECT_CRITERIA';
export const REMOVE = 'REMOVE';

export const SET_WIZARD_OPEN = 'SET_WIZARD_OPEN';
export const SET_WIZARD_CLOSED = 'SET_WIZARD_CLOSED';
export const SET_ACTIVE_CONTEXT = 'SET_ACTIVE_CONTEXT';
export const CLEAR_ACTIVE_CONTEXT = 'CLEAR_ACTIVE_CONTEXT';
