# Uncomment the following to turn on full SQL debugging
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.type=trace
#spring.jpa.properties.hibernate.use_sql_comments=true
# Uncomment the following for very verbose Spring boot autowire logging.
#logging.level.org.springframework=DEBUG
# Keep the db connection alive. (https://precisionmedicineinitiative.atlassian.net/browse/RW-235)
# Note: We're using a flat namespace for spring datasource because we have a
# custom data source configuration (needed in order to support multiple data
# sources). Putting properties onto "spring.datasource.tomcat" (as you might
# see in Spring documentation) will do nothing. See WorkbenchDbConfig and
# CdrDbConfig.
spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    test-on-borrow: true
    time-between-eviction-runs-millis: 3600000
    validation-query: SELECT 1
    initial-size: 5
    max-idle: 5
    min-idle: 1
    driver-class-name: ${DB_DRIVER:com.mysql.jdbc.Driver}
    url: ${DB_CONNECTION_STRING:jdbc:mysql://127.0.0.1/workbench?useSSL=false}
    username: ${WORKBENCH_DB_USER:workbench}
    password: ${WORKBENCH_DB_PASSWORD:wb-notasecret}
  # Disable liquibase because DB migration handled by anothe gradle task.
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.pmiops.workbench.cdr.MySQLDialect
  liquibase:
    enabled: false

cdr:
  datasource:
    url: ${CDR_DB_CONNECTION_STRING:jdbc:mysql://127.0.0.1/workbench?useSSL=false}
    username: ${CDR_DB_USER:workbench}
    password: ${CDR_DB_PASSWORD:wb-notasecret}
# See https://docs.spring.io/spring-boot/docs/2.3.9.RELEASE/reference/html/production-ready-features.html
# and https://precisionmedicineinitiative.atlassian.net/browse/RW-1478
# Disable all spring-boot endpoints unless specifically necessary
management:
  endpoints:
    enabled-by-default: false
server:
  port: 8081

  # Workbench API server properities
workbench:
  property:
    is-local: false
