# copied from https://github.com/DataBiosphere/calhoun/blob/dev/static/api-docs.yaml
openapi: 3.0.0
info:
  title: Calhoun
  description: |
    Notebook preview service.
  # Follow semantic versioning https://semver.org/
  version: "0.0.1"
  license:
    name: BSD
    url: http://opensource.org/licenses/BSD-3-Clause
tags:
  - name: convert
    description: Conversion endpoints.
  - name: service_info
    description: Service Info API
security:
  - googleoauth:
      - openid
      - email
      - profile

##########################################################################################
## PATHS
##########################################################################################
paths:

  ## Service Info paths ##

  /status:
    get:
      summary: Gets system status
      responses:
        "200":
          description: System ok
          content:
            text/plain:
              schema:
                type: string
                example: OK
        "500":
          description: System not ok
          content:
            text/plain:
              schema:
                type: string
      operationId: getSystemStatus
      tags:
        - service_info
      security: []


  ## Conversion paths ##

  /api/convert:
    post:
      summary: Converts Jupyter Notebook
      description: Converts a Jupyter Notebook file to HTML. Accepts the content of .ipynb file in the request body.
      operationId: convertNotebook
      tags:
        - convert
      requestBody:
        content:
          application/json:
            schema:
              type: string
              format: binary
              example: {"cells":[{"cell_type":"code","execution_count":1,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Hello World!\n"]}],"source":["print(\"Hello World!\")"]}],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.9"},"toc":{"base_numbering":1,"nav_menu":{},"number_sections":true,"sideBar":true,"skip_h1_title":false,"title_cell":"Table of Contents","title_sidebar":"Contents","toc_cell":false,"toc_position":{},"toc_section_display":true,"toc_window_display":false}},"nbformat":4,"nbformat_minor":2}
      responses:
        "200":
          description: HTML conversion
          content:
            text/html:
              schema:
                type: string
                format: binary
  /api/convert/rmd:
    post:
      summary: Converts R Markdown
      description: Converts an R Markdown file to HTML. Accepts the content of an .Rmd file in the request body.
      operationId: convertRmd
      tags:
        - convert
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              format: binary
              example: |
                ---
                title: "test-rmd"
                output: html_document
                ---

                ```{r setup, include=FALSE}
                knitr::opts_chunk$set(echo = TRUE)
                ```

                ## R Markdown

                This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

                When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

                ```{r cars}
                summary(cars)
                ```

                ## Including Plots

                You can also embed plots, for example:

                ```{r pressure, echo=FALSE}
                plot(pressure)
                ```

                Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
      responses:
        "200":
          description: HTML conversion
          content:
            text/html:
              schema:
                type: string
                format: binary


##########################################################################################
## COMPONENTS
##########################################################################################

components:
  securitySchemes:
    googleoauth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            openid: open id authorization
            email: email authorization
            profile: profile authorization