#This file provide the end points for moodle interactions
# Moodle API information can be found at :
# https://docs.moodle.org/dev/Web_service_API_functions

openapi: 3.0.1
info:
  title: Moodle
  description: |
    Service for Moodle Interactions.
  version: "0.1"

# We use aoudev.nnlm.gov for Test, Local, and Staging
servers:
  - url: https://aou.nnlm.gov/webservice/rest

##########################################################################################
## PATHS
##########################################################################################
paths:
  /server.php?wsfunction=local_workbenchapiv2_check_user_badge:
    get:
      tags:
        - Moodle
      summary: Get information of badges earned/completed by user.
      operationId: getMoodleBadgeV2
      parameters:
        - name: moodlewsrestformat
          in: query
          description: Format of the response which will be json for AoU
          required: true
          schema:
            type: string
        - name: email
          in: query
          schema:
            type: string
        - name: wstoken
          in: query
          description: Secret Token associated with All of us
          required: true
          schema:
            type: string
      responses:
        200:
          description: Badge /error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserBadgeResponseV2'
        400:
          description: Bad request
          content: {}
        500:
          description: Moodle Internal Error
          content: {}
      security:
        - AdminSecurity: []

##########################################################################################
## COMPONENTS
##########################################################################################
components:
  schemas:
    UserBadgeResponseV2:
      type: object
      properties:
        id:
          type: integer
          description: User id
        username:
          type: string
          description: Moodle username
        ret:
          $ref: '#/components/schemas/BadgeDetailsV2'
        dua:
          $ref: '#/components/schemas/BadgeDetailsV2'
        exception:
          type: string
        errorcode:
          type: string
        message:
          type: string
          description: A message describing the error
    BadgeDetailsV2:
      type: object
      properties:
        valid:
          type: boolean
          description: Whether the badge is valid
        lastissued:
          type: integer
          description: Date of latest issued badge. As a stringy epoch in SECONDS.
          format: int64
        dateexpire:
          type: integer
          description: Latest expiration of obtained badge. As a stringy epoch in
            SECONDS.
          format: int64
        message:
          type: string
          description: General API message
        globalexpiration:
          type: integer
          description: Global expiration, overrides badge expiration date. As a stringy
            epoch in SECONDS.
          format: int64
