#This file provide the end points for interaction with RDR


swagger: '2.0'

info:
  title: RDR
  description: |
    Service for RDR Interactions.
  version: "0.1"
#The host will get updated as per the environment it will be pmi-drc-api-test for dev and test
host: "pmi-drc-api-test.appspot.com"
schemes:
  - "https"
basePath: /

securityDefinitions:
  googleoauth:
    type: oauth2
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    flow: implicit
    scopes:
      openid: open id authorization
      email: email authorization
      profile: profile authorization

security:
  - googleoauth:
    - openid
    - email
    - profile
    - https://www.googleapis.com/auth/devstorage.full_control

produces:
  - application/json

##########################################################################################
## PATHS
##########################################################################################

paths:
  /rdr/v1/workbench/directory/workspaces:
    post:
      description: Submits one or more workspace snapshots for storage in the RDR.
      tags:
        - Rdr
      consumes:
        - application/json
      operationId: exportWorkspaces
      parameters:
        - in: query
          name: backfill
          type: boolean
          required: false
        - in: body
          required: true
          name: workspaces
          schema:
            type: array
            items:
              $ref: "#/definitions/Workspace"
      responses:
        200:
          description: successful operation

  /rdr/v1/workbench/directory/researchers:
    post:
      description: Submits one or more researcher snapshots for storage in the RDR.
      tags:
        - Rdr
      operationId: exportResearchers
      consumes:
        - application/json
      parameters:
        - in: body
          required: true
          name: researchers
          schema:
            type: array
            items:
              $ref: "#/definitions/Researcher"
      responses:
        200:
          description: successful operation



definitions:
  Workspace:
    type: object
    properties:
      workspaceId:
        type: integer
      name:
        type: string
      creator:
        description: Information about the creator of the workspace
        $ref: "#/definitions/WorkspaceCreator"
      creationTime:
        type: string
        format: date-time
      modifiedTime:
        type: string
        format: date-time
      status:
        type: string
        description: INACTIVE Represents the workspace is deleted or Pending Deletion
        enum:
          - ACTIVE
          - INACTIVE
      workspaceUsers:
        type: array
        items:
          $ref: '#/definitions/WorkspaceUser'
      excludeFromPublicDirectory:
        type: boolean
        description: Set to true if the creator of the workspace is an Operational User
      diseaseFocusedResearch:
        type: boolean
      diseaseFocusedResearchName:
        type: string
      methodsDevelopment:
        type: boolean
      controlSet:
        type: boolean
      ancestry:
        type: boolean
      socialBehavioral:
        type: boolean
      populationHealth:
        type: boolean
      drugDevelopment:
        type: boolean
      commercialPurpose:
        type: boolean
      educational:
        type: boolean
      ethicalLegalSocialImplications:
        type: boolean
      otherPurpose:
        type: boolean
      otherPurposeDetails:
        type: string
      scientificApproaches:
        type: string
      intendToStudy:
        type: string
      findingsFromStudy:
        type: string
      focusOnUnderrepresentedPopulations:
        description: Represents if researchers has selected YES for question Will your study focus
          on any historically underrepresented populations
        type: boolean
      reviewRequested:
        type: boolean
      workspaceDemographic:
        $ref: '#/definitions/WorkspaceDemographic'
      cdrVersionName:
        type: string
      accessTier:
        $ref: '#/definitions/AccessTier'

  WorkspaceDemographic:
    type: object
    properties:
      raceEthnicity:
        type: array
        items:
          type: string
          enum:
            - UNSET
            - AIAN
            - ASIAN
            - HISPANIC
            - NHPI
            - MENA
            - AA
            - MULTI
      age:
        type: array
        items:
          type: string
          enum:
            - UNSET
            - AGE_0_11
            - AGE_12_17
            - AGE_65_74
            - AGE_75_AND_MORE
      sexAtBirth:
        type: string
        enum:
          - UNSET
          - INTERSEX
      genderIdentity:
        type: string
        enum:
          - UNSET
          - OTHER_THAN_MAN_WOMAN
      sexualOrientation:
        type: string
        enum:
          - UNSET
          - OTHER_THAN_STRAIGHT
      geography:
        type: string
        enum:
          - UNSET
          - RURAL
      disabilityStatus:
        type: string
        enum:
          - UNSET
          - DISABILITY
      accessToCare:
        type: string
        enum:
          - UNSET
          - NOT_EASILY_ACCESS_CARE
      educationLevel:
        type: string
        enum:
          - UNSET
          - LESS_THAN_HIGH_SCHOOL
      incomeLevel:
        type: string
        enum:
          - UNSET
          - BELOW_FEDERAL_POVERTY_LEVEL_200_PERCENT
      others:
        type: string

  WorkspaceUser:
    type: object
    properties:
      userId:
        type: integer
      role:
        type: string
        enum:
          - READER
          - WRITER
          - OWNER
      status:
        type: string
        description: Workspace User Status
        enum:
          - ACTIVE
          - INACTIVE

  WorkspaceCreator:
    type: object
    description: Details for workspace creator
    required:
      - userId
      - givenName
      - familyName
    properties:
      userId:
        description: Database ID from Table User for creator
        type: integer
        format: int64
      givenName:
        type: string
      familyName:
        type: string

  Researcher:
    type: object
    properties:
      userId:
        type: integer
      creationTime:
        type: string
        format: date-time
      modifiedTime:
        type: string
        format: date-time
      givenName:
        type: string
      familyName:
        type: string
      streetAddress1:
        type: string
      streetAddress2:
        type: string
      city:
        type: string
      state:
        type: string
      zipCode:
        type: string
      country:
        type: string
      ethnicity:
        $ref: '#/definitions/Ethnicity'
      gender:
        type: array
        items:
          $ref: '#/definitions/Gender'
      race:
        type: array
        items:
          $ref: '#/definitions/Race'
      sexAtBirth:
        type: array
        items:
          $ref: '#/definitions/SexAtBirth'
      identifiesAsLgbtq:
        type: boolean
      lgbtqIdentity:
        type: string
      education:
        $ref: '#/definitions/Education'
      disability:
        $ref: '#/definitions/Disability'
      degrees:
        type: array
        items:
          $ref: '#/definitions/Degree'
      verifiedInstitutionalAffiliation:
        $ref: '#/definitions/ResearcherVerifiedInstitutionalAffiliation'
      email:
        type: string
      accessTierShortNames:
        type: array
        items:
          $ref: '#/definitions/AccessTier'

  ResearcherVerifiedInstitutionalAffiliation:
    type: object
    required:
      - institutionShortName
      - institutionDisplayName
      - institutionalRole
    properties:
      institutionShortName:
        type: string
        description: The unique Short Name of the Institution where the user has a Verified Affiliation, such as 'Broad'
      institutionDisplayName:
        type: string
        description: The Display Name of the Institution where the user has a Verified Affiliation, such as 'Broad Institute'
      institutionalRole:
        type: string
        description: The user's Institutional Role at this Institution, as text

  AccessTier:
    type: string
    enum:
      - UNSET
      - REGISTERED
      - CONTROLLED

  Ethnicity:
    type: string
    enum:
      - HISPANIC
      - NOT_HISPANIC
      - PREFER_NOT_TO_ANSWER

  Gender:
    type: string
    enum:
      - MAN
      - WOMAN
      - NON_BINARY
      - TRANSGENDER
      - NONE_DESCRIBE_ME
      - PREFER_NOT_TO_ANSWER

  Race:
    type: string
    enum:
      - AIAN
      - ASIAN
      - AA
      - NHOPI
      - WHITE
      - NONE
      - PREFER_NOT_TO_ANSWER

  SexAtBirth:
    type: string
    enum:
      - FEMALE
      - INTERSEX
      - MALE
      - NONE_OF_THESE_DESCRIBE_ME
      - PREFER_NOT_TO_ANSWER

  SexualOrientation:
    type: string
    enum:
      - BISEXUAL
      - GAY
      - LESBIAN
      - STRAIGHT
      - NONE_OF_THESE_DESCRIBE_ME
      - PREFER_NOT_TO_ANSWER

  Education:
    type: string
    enum:
      - NO_EDUCATION
      - GRADES_1_12
      - COLLEGE_GRADUATE
      - UNDERGRADUATE
      - MASTER
      - DOCTORATE
      - PREFER_NOT_TO_ANSWER

  Disability:
    type: string
    enum:
      - "YES"
      - "NO"
      - PREFER_NOT_TO_ANSWER

  Degree:
    type: string
    enum:
      - UNSET
      - PHD
      - MD
      - JD
      - EDD
      - MSN
      - MS
      - MA
      - MBA
      - ME
      - MSW
      - MPH
      - BA
      - BS
      - BSN

  DemographicSurveyV2:
    type: object
    properties:
      completionTime:
        type: string
        format: date-time
        description: The time the user most recently completed the survey
      ethnicCategories:
        type: array
        items:
          "$ref": "#/definitions/EthnicCategory"
      ethnicityAiAnOtherText:
        type: string
        description: American Indian or Alaska Native /  None of these fully describe me, and I want to specify.  Max length 200.
      ethnicityAsianOtherText:
        type: string
        description: Asian / None of these fully describe me, and I want to specify.  Max length 200.
      ethnicityOtherText:
        type: string
        description: None of these fully describe me, and I want to specify.  Max length 200.
      genderIdentities:
        type: array
        items:
          "$ref": "#/definitions/GenderIdentityV2"
      genderOtherText:
        type: string
        description: None of these fully describe me, and I want to specify.  Max length 200.
      sexualOrientations:
        type: array
        items:
          "$ref": "#/definitions/SexualOrientationV2"
      orientationOtherText:
        type: string
        description: None of these fully describe me, and I want to specify.  Max length 200.
      sexAtBirth:
        "$ref": "#/definitions/SexAtBirthV2"
      sexAtBirthOtherText:
        type: string
        description: None of these fully describe me, and I want to specify.  Max length 200.
      yearOfBirth:
        type: integer
      yearOfBirthPreferNot:
        type: boolean
      disabilityHearing:
        "$ref": "#/definitions/YesNoPreferNot"
        description: >
          Are you deaf or do you have serious difficulty hearing?
          (Note: Some people who are deaf or have serious difficulty
          hearing use assistive devices to communicate by phone.)
      disabilitySeeing:
        "$ref": "#/definitions/YesNoPreferNot"
        description: Are you blind or do you have serious difficulty seeing, even when wearing glasses?
      disabilityConcentrating:
        "$ref": "#/definitions/YesNoPreferNot"
        description: >
          Because of a physical, cognitive, or emotional condition,
          do you have serious difficulty concentrating, remembering, or making decisions?
      disabilityWalking:
        "$ref": "#/definitions/YesNoPreferNot"
        description: Do you have serious difficulty walking or climbing stairs?
      disabilityDressing:
        "$ref": "#/definitions/YesNoPreferNot"
        description: Do you have difficulty dressing or bathing?
      disabilityErrands:
        "$ref": "#/definitions/YesNoPreferNot"
        description: >
          Because of a physical, mental, or emotional condition,
          do you have difficulty doing errands alone such as visiting
          a doctor’s office or shopping?
      disabilityOtherText:
        type: string
        description: >
          Do you have a physical, cognitive, and/or emotional condition that
          substantially inhibits one or more life activities not specified
          through the above questions, and want to share more? Please describe.
      education:
        "$ref": "#/definitions/EducationV2"
      disadvantaged:
        "$ref": "#/definitions/YesNoPreferNot"
        description: >
          Are you an individual from a disadvantaged background,
          as defined by NIH Diversity in Extramural Programs?

  EthnicCategory:
    type: string
    description: 'Which categories describe you? (Select all that apply). Note, you may select more than one group.'
    enum:
      - AI_AN                 # American Indian or Alaska Native (no additional qualifier)
      - AI_AN_CENTRAL_SOUTH   # American Indian or Alaska Native / Central or South American Indian
      - AI_AN_OTHER           # American Indian or Alaska Native / None of these fully describe me, and I want to specify
      - ASIAN
      - ASIAN_INDIAN
      - ASIAN_CAMBODIAN
      - ASIAN_CHINESE
      - ASIAN_FILIPINO
      - ASIAN_HMONG
      - ASIAN_JAPANESE
      - ASIAN_KOREAN
      - ASIAN_LAO
      - ASIAN_PAKISTANI
      - ASIAN_VIETNAMESE
      - ASIAN_OTHER           # Asian / None of these fully describe me, and I want to specify
      - BLACK                 # Black, African American, or of African descent
      - HISPANIC              # Hispanic, Latino, or Spanish descent
      - MENA                  # Middle Eastern or North African
      - NHPI                  # Native Hawaiian or other Pacific Islander
      - WHITE                 # White, or of European descent
      - OTHER                 # None of these fully describe me, and I want to specify
      - PREFER_NOT_TO_ANSWER

  GenderIdentityV2:
    type: string
    description: 'Which terms best express how you describe your current gender identity? (Select all that apply)'
    enum:
      - GENDERQUEER
      - MAN
      - NON_BINARY
      - QUESTIONING           # Questioning or unsure of my gender identity
      - TRANS_MAN             # Trans man/Transgender man
      - TRANS_WOMAN           # Trans woman/Transgender woman
      - TWO_SPIRIT
      - WOMAN
      - OTHER                 # None of these fully describe me, and I want to specify
      - PREFER_NOT_TO_ANSWER

  SexualOrientationV2:
    type: string
    description: 'Which terms best express how you describe your current sexual orientation? (Select all that apply)'
    enum:
      - ASEXUAL
      - BISEXUAL
      - GAY
      - LESBIAN
      - POLYSEXUAL            # Polysexual, omnisexual, or pansexual
      - QUEER
      - QUESTIONING           # Questioning or unsure of my sexual orientation
      - SAME_GENDER           # Same-gender loving
      - STRAIGHT              # Straight or heterosexual
      - TWO_SPIRIT
      - OTHER                 # None of these fully describe me, and I want to specify
      - PREFER_NOT_TO_ANSWER

  SexAtBirthV2:
    type: string
    description: 'What was the sex assigned to you at birth, such as on your original birth certificate?'
    enum:
      - FEMALE
      - INTERSEX
      - MALE
      - OTHER                 # None of these fully describe me, and I want to specify
      - PREFER_NOT_TO_ANSWER

  EducationV2:
    type: string
    description: 'Highest Level of Education Completed'
    enum:
      - NO_EDUCATION          # Never attended school/No formal education
      - GRADES_1_12           # Primary/Middle School/High School (Grades 1 through 12/GED)
      - UNDERGRADUATE         # Some college, Associate Degree or Technical School (1 to 3 years) or current undergraduate student
      - COLLEGE_GRADUATE      # College graduate (4 years or more) or current post-graduate trainee
      - MASTER
      - DOCTORATE
      - PREFER_NOT_TO_ANSWER

  YesNoPreferNot:
    type: string
    enum:
      - 'YES'   # quotes needed so Swagger/YAML doesn't autoconvert this to "true"
      - 'NO'    # quotes needed so Swagger/YAML doesn't autoconvert this to "false"
      - PREFER_NOT_TO_ANSWER
