#This file provide the end points for interaction with RDR


swagger: '2.0'

info:
  title: RDR
  description: |
    Service for RDR Interactions.
  version: "0.1"
#The host will get updated as per the environment it will be pmi-drc-api-test for dev and test
host: "pmi-drc-api-test.appspot.com"
schemes:
  - "https"
basePath: /

securityDefinitions:
  googleoauth:
    type: oauth2
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    flow: implicit
    scopes:
      openid: open id authorization
      email: email authorization
      profile: profile authorization

security:
  - googleoauth:
    - openid
    - email
    - profile
    - https://www.googleapis.com/auth/devstorage.full_control

produces:
  - application/json

##########################################################################################
## PATHS
##########################################################################################

paths:
  /rdr/v1/workbench/directory/workspaces:
    post:
      description: Submits one or more workspace snapshots for storage in the RDR.
      tags:
        - Rdr
      consumes:
        - application/json
      operationId: exportWorkspaces
      parameters:
        - in: query
          name: backfill
          type: boolean
          required: false
        - in: body
          required: true
          name: workspaces
          schema:
            type: array
            items:
              $ref: "#/definitions/Workspace"
      responses:
        200:
          description: successful operation

  /rdr/v1/workbench/directory/researchers:
    post:
      description: Submits one or more researcher snapshots for storage in the RDR.
      tags:
        - Rdr
      operationId: exportResearchers
      consumes:
        - application/json
      parameters:
        - in: body
          required: true
          name: researchers
          schema:
            type: array
            items:
              $ref: "#/definitions/Researcher"
      responses:
        200:
          description: successful operation



definitions:
  Workspace:
    type: object
    properties:
      workspaceId:
        type: integer
      name:
        type: string
      creator:
        description: Information about the creator of the workspace
        $ref: "#/definitions/WorkspaceCreator"
      creationTime:
        type: string
        format: date-time
      modifiedTime:
        type: string
        format: date-time
      status:
        type: string
        description: INACTIVE Represents the workspace is deleted or Pending Deletion
        enum:
          - ACTIVE
          - INACTIVE
      workspaceUsers:
        type: array
        items:
          $ref: '#/definitions/WorkspaceUser'
      excludeFromPublicDirectory:
        type: boolean
        description: Set to true if the creator of the workspace is an Operational User
      diseaseFocusedResearch:
        type: boolean
      diseaseFocusedResearchName:
        type: string
      methodsDevelopment:
        type: boolean
      controlSet:
        type: boolean
      ancestry:
        type: boolean
      socialBehavioral:
        type: boolean
      populationHealth:
        type: boolean
      drugDevelopment:
        type: boolean
      commercialPurpose:
        type: boolean
      educational:
        type: boolean
      ethicalLegalSocialImplications:
        type: boolean
      otherPurpose:
        type: boolean
      otherPurposeDetails:
        type: string
      scientificApproaches:
        type: string
      intendToStudy:
        type: string
      findingsFromStudy:
        type: string
      focusOnUnderrepresentedPopulations:
        description: Represents if researchers has selected YES for question Will your study focus
          on any historically underrepresented populations
        type: boolean
      reviewRequested:
        type: boolean
      workspaceDemographic:
        $ref: '#/definitions/WorkspaceDemographic'
      cdrVersionName:
        type: string
      accessTier:
        $ref: '#/definitions/AccessTier'

  WorkspaceDemographic:
    type: object
    properties:
      raceEthnicity:
        type: array
        items:
          type: string
          enum:
            - UNSET
            - AIAN
            - ASIAN
            - HISPANIC
            - NHPI
            - MENA
            - AA
            - MULTI
      age:
        type: array
        items:
          type: string
          enum:
            - UNSET
            - AGE_0_11
            - AGE_12_17
            - AGE_65_74
            - AGE_75_AND_MORE
      sexAtBirth:
        type: string
        enum:
          - UNSET
          - INTERSEX
      genderIdentity:
        type: string
        enum:
          - UNSET
          - OTHER_THAN_MAN_WOMAN
      sexualOrientation:
        type: string
        enum:
          - UNSET
          - OTHER_THAN_STRAIGHT
      geography:
        type: string
        enum:
          - UNSET
          - RURAL
      disabilityStatus:
        type: string
        enum:
          - UNSET
          - DISABILITY
      accessToCare:
        type: string
        enum:
          - UNSET
          - NOT_EASILY_ACCESS_CARE
      educationLevel:
        type: string
        enum:
          - UNSET
          - LESS_THAN_HIGH_SCHOOL
      incomeLevel:
        type: string
        enum:
          - UNSET
          - BELOW_FEDERAL_POVERTY_LEVEL_200_PERCENT
      others:
        type: string

  WorkspaceUser:
    type: object
    properties:
      userId:
        type: integer
      role:
        type: string
        enum:
          - READER
          - WRITER
          - OWNER
      status:
        type: string
        description: Workspace User Status
        enum:
          - ACTIVE
          - INACTIVE

  WorkspaceCreator:
    type: object
    description: Details for workspace creator
    required:
      - userId
      - givenName
      - familyName
    properties:
      userId:
        description: Database ID from Table User for creator
        type: integer
        format: int64
      givenName:
        type: string
      familyName:
        type: string

  Researcher:
    type: object
    properties:
      userId:
        type: integer
      creationTime:
        type: string
        format: date-time
      modifiedTime:
        type: string
        format: date-time
      givenName:
        type: string
      familyName:
        type: string
      streetAddress1:
        type: string
      streetAddress2:
        type: string
      city:
        type: string
      state:
        type: string
      zipCode:
        type: string
      country:
        type: string
      ethnicity:
        $ref: '#/definitions/Ethnicity'
      gender:
        type: array
        items:
          $ref: '#/definitions/Gender'
      race:
        type: array
        items:
          $ref: '#/definitions/Race'
      sexAtBirth:
        type: array
        items:
          $ref: '#/definitions/SexAtBirth'
      identifiesAsLgbtq:
        type: boolean
      lgbtqIdentity:
        type: string
      education:
        $ref: '#/definitions/Education'
      disability:
        $ref: '#/definitions/Disability'
      degrees:
        type: array
        items:
          $ref: '#/definitions/Degree'
      verifiedInstitutionalAffiliation:
        $ref: '#/definitions/ResearcherVerifiedInstitutionalAffiliation'
      email:
        type: string
      accessTierShortNames:
        type: array
        items:
          $ref: '#/definitions/AccessTier'

  ResearcherVerifiedInstitutionalAffiliation:
    type: object
    required:
      - institutionShortName
      - institutionDisplayName
      - institutionalRole
    properties:
      institutionShortName:
        type: string
        description: The unique Short Name of the Institution where the user has a Verified Affiliation, such as 'Broad'
      institutionDisplayName:
        type: string
        description: The Display Name of the Institution where the user has a Verified Affiliation, such as 'Broad Institute'
      institutionalRole:
        type: string
        description: The user's Institutional Role at this Institution, as text

  AccessTier:
    type: string
    enum:
      - UNSET
      - REGISTERED
      - CONTROLLED

  Ethnicity:
    type: string
    enum:
      - HISPANIC
      - NOT_HISPANIC
      - PREFER_NOT_TO_ANSWER

  Gender:
    type: string
    enum:
      - MAN
      - WOMAN
      - NON_BINARY
      - TRANSGENDER
      - NONE_DESCRIBE_ME
      - PREFER_NOT_TO_ANSWER

  Race:
    type: string
    enum:
      - AIAN
      - ASIAN
      - AA
      - NHOPI
      - WHITE
      - NONE
      - PREFER_NOT_TO_ANSWER

  SexAtBirth:
    type: string
    enum:
      - FEMALE
      - INTERSEX
      - MALE
      - NONE_OF_THESE_DESCRIBE_ME
      - PREFER_NOT_TO_ANSWER

  SexualOrientation:
    type: string
    enum:
      - BISEXUAL
      - GAY
      - LESBIAN
      - STRAIGHT
      - NONE_OF_THESE_DESCRIBE_ME
      - PREFER_NOT_TO_ANSWER

  Education:
    type: string
    enum:
      - NO_EDUCATION
      - GRADES_1_12
      - COLLEGE_GRADUATE
      - UNDERGRADUATE
      - MASTER
      - DOCTORATE
      - PREFER_NOT_TO_ANSWER

  Disability:
    type: string
    enum:
      - "YES"
      - "NO"
      - PREFER_NOT_TO_ANSWER

  Degree:
    type: string
    enum:
      - UNSET
      - PHD
      - MD
      - JD
      - EDD
      - MSN
      - MS
      - MA
      - MBA
      - ME
      - MSW
      - MPH
      - BA
      - BS
      - BSN
