# Partialy copied from https://github.com/broadinstitute/firecloud-orchestration/blob/develop/src/main/resources/swagger/api-docs.yaml
# Once workbench use Java 11, we can consider switch to use SAM generated Client Library.
openapi: 3.0.1
info:
  title: Sam
  description: |
    Workbench identity and access management.
  termsOfService: https://github.com/broadinstitute/sam
  license:
    name: BSD
    url: http://opensource.org/licenses/BSD-3-Clause
  version: "0.1"
servers:
  - url: /
security:
  - googleoauth:
      - openid
      - email
      - profile
paths:
  /api/google/v1/user/petServiceAccount/{project}:
    get:
      tags:
        - Google
      summary: gets the pet service account for the specified user
      operationId: getPetServiceAccount
      parameters:
        - name: project
          in: path
          description: Google project of the pet
          required: true
          schema:
            type: string
      responses:
        200:
          description: user pet service account
          content:
            application/json:
              schema:
                type: string
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
  /api/groups/v1/{groupName}/{policyName}:
    get:
      tags:
        - Group
      summary: Get email addresses for members of the policy
      operationId: GetGroupPolicyEmails
      parameters:
        - name: groupName
          in: path
          description: Name of group
          required: true
          schema:
            type: string
        - name: policyName
          in: path
          description: Name of policy
          required: true
          schema:
            type: string
            enum:
              - member
              - admin
      responses:
        200:
          description: Email addresses in the policy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfEmails'
        404:
          description: Group could not be found or you do not have the required permissions
            on this group
          content: {}
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
    put:
      tags:
        - Group
      summary: Overwrite email addresses of members of the policy
      operationId: OverwriteGroupPolicyEmails
      parameters:
        - name: groupName
          in: path
          description: Name of group
          required: true
          schema:
            type: string
        - name: policyName
          in: path
          description: Name of policy
          required: true
          schema:
            type: string
            enum:
              - member
              - admin
      requestBody:
        description: The list of emails
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/ArrayOfEmails'
        required: true
      responses:
        201:
          description: Policy successfully updated
          content: {}
        404:
          description: Group does not exist or you are not a member of the policy
            for the group
          content: {}
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
      x-codegen-request-body-name: emailAddresses
components:
  schemas:
    ArrayOfEmails:
      type: array
      description: An array of email addresses
      example:
        - person@company.com
        - group_name@company.com
        - foo@bar.com
      items:
        type: string
    ErrorReport:
      required:
        - causes
        - message
        - source
        - stackTrace
      type: object
      properties:
        source:
          type: string
          description: service causing error
        message:
          type: string
          description: what went wrong
        exceptionClass:
          type: string
          description: class of exception thrown
        statusCode:
          type: integer
          description: HTTP status code
        causes:
          type: array
          description: errors triggering this one
          items:
            $ref: '#/components/schemas/ErrorReport'
        stackTrace:
          type: array
          description: stack trace
          items:
            $ref: '#/components/schemas/StackTraceElement'
      description: ""
    StackTraceElement:
      required:
        - className
        - fileName
        - lineNumber
        - methodName
      type: object
      properties:
        className:
          type: string
          description: class name
        methodName:
          type: string
          description: method name
        fileName:
          type: string
          description: source file name
        lineNumber:
          type: integer
          description: line number
      description: ""
  securitySchemes:
    googleoauth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            openid: open id authorization
            email: email authorization
            profile: profile authorization
