#This file provide the end points for Tanagra interactions
# Tanagra API information can be found at :
# https://github.com/DataBiosphere/tanagra

openapi: 3.0.1
info:
  title: Tanagra
  description: |
    Service for Tanagra Interactions.
  version: "0.1"

# We use localhost:3000 for Local
servers:
  - url: http://localhost:3000

##########################################################################################
## PATHS
##########################################################################################
paths:
  /v2/studies:
    post:
      tags:
        - Tanagra
      summary: Save a Study(equivalent to AoU workspace) in Tanagra.
      operationId: createStudy
      requestBody:
        description: Format of the response which will be json for AoU
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudyCreateInfo'
      responses:
        200:
          description: Newly created Study / Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Study'
                
  "/v2/studies/{studyId}/cohorts":
    parameters:
      - $ref: "#/components/parameters/StudyId"
    get:
      parameters:
        - $ref: "#/components/parameters/Offset"
        - $ref: "#/components/parameters/Limit"
      summary: List all cohorts in a study
      operationId: listCohorts
      tags:
        - Tanagra
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CohortList"
        500:
          $ref: "#/components/responses/ServerError"
                
  /v2/underlays/{underlayName}/describeExport:
    post:
      tags:
        - Tanagra
      summary: Describe the entities and attributes that will be included in export query
      operationId: describeExport
      parameters:
        - in: path
          name: underlayName
          description: underlayName
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExportPreviewRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntityOutputPreviewList"

##########################################################################################
## COMPONENTS
##########################################################################################
components:
  parameters:
    StudyId:
      name: studyId
      in: path
      description: ID of the study
      required: true
      schema:
        type: string
        
    Offset:
      name: offset
      in: query
      description: The number of items to skip before starting to collect the result set.
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
        
    Limit:
      name: limit
      in: query
      description: The maximum number of items to return. Defaults to 50.
      required: false
      schema:
        type: integer
        minimum: 1
        default: 50
        
  securitySchemes:
    oauth:
      type: apiKey
      in: header
      name: Authorization
      
  schemas:
    CohortList:
      type: array
      items:
        $ref: "#/components/schemas/Cohort"
        
    Cohort:
      type: object
      properties:
        id:
          type: string
          description: ID of the cohort, immutable
        revisionId:
          type: string
          description: ID of a frozen cohort revision, immutable
        underlayName:
          type: string
          description: Name of the underlay, immutable
        displayName:
          type: string
          description: Human readable name of the cohort
        description:
          type: string
          description: Description of the cohort
        criteriaGroupSections:
          type: array
          description: Criteria group sections that define the entity filter
          items:
            $ref: "#/components/schemas/CriteriaGroupSection"
        created:
          description: Timestamp of when the cohort was created
          type: string
          format: date-time
        createdBy:
          description: Email of user who created cohort
          type: string
        lastModified:
          description: Timestamp of when the cohort was last modified
          type: string
          format: date-time
        isDeleted:
          type: boolean
      required:
        - id
        - underlayName
        - displayName
        - criteriaGroups
        - created
        - createdBy
        - lastModified

    CriteriaGroupSection:
      type: object
      description: Section of criteria groups and boolean logic operators to combine them
      properties:
        id:
          type: string
          description: ID of the section, immutable
        displayName:
          type: string
          description: Name of the section
        criteriaGroups:
          type: array
          description: |
            For a temporal section, this is the set of groups that define the first block.
            For a non-temporal section, the set of groups are the union of this list and the secondBlockCriteriaGroups list.
          items:
            $ref: "#/components/schemas/CriteriaGroup"
        firstBlockReducingOperator:
          $ref: "#/components/schemas/ReducingOperator"
        secondBlockCriteriaGroups:
          type: array
          description: |
            For a temporal section, this is the set of groups that define the second block.
            For a non-temporal section, the set of groups are the union of this list and the criteriaGroups list.
          items:
            $ref: "#/components/schemas/CriteriaGroup"
        secondBlockReducingOperator:
          $ref: "#/components/schemas/ReducingOperator"
        operator:
          type: string
          description: Operator to use when combining the criteria groups in the section
          enum: ["AND", "OR", "DURING_SAME_ENCOUNTER", "NUM_DAYS_BEFORE", "NUM_DAYS_AFTER", "WITHIN_NUM_DAYS"]
        operatorValue:
          type: integer
          description: Value associated with the operator (e.g. num days)
        excluded:
          type: boolean
          description: True to exclude the section, false to include it
        disabled:
          type: boolean
          description: True to disable the section
          default: false
      required:
        - id
        - displayName
        - criteriaGroups
        - operator
        - excluded

    ReducingOperator:
      description: |
        Reducing operator for criteria groups blocks.
        Only applies for a temporal section.
      type: string
      enum: ["ANY", "FIRST_MENTION_OF", "LAST_MENTION_OF"]

    CriteriaGroup:
      type: object
      description: Group of related criteria (primary + modifiers)
      properties:
        id:
          type: string
          description: ID of the group, immutable
        displayName:
          type: string
          description: Name of the group
        criteria:
          type: array
          description: Set of criteria in the group
          items:
            $ref: "#/components/schemas/Criteria"
        disabled:
          type: boolean
          description: True to disable the group
          default: false
      required:
        - id
        - displayName
        - criteria

    Criteria:
      type: object
      description: Single criteria for a cohort or feature set definition
      properties:
        id:
          type: string
          description: ID of the criteria, immutable
        displayName:
          type: string
          description: Name of the criteria
        pluginName:
          type: string
          description: Name of the plugin that generated this criteria
        pluginVersion:
          type: integer
          description: Version of the plugin that generated this criteria
        predefinedId:
          type: string
          description: Id of the predefined criteria in the config
        selectorOrModifierName:
          type: string
          description: Name of the selector or modifier used by this config
        selectionData:
          type: string # JSON formatted, previously base64 Protobuf formatted
          description: Serialized plugin-specific representation of the user's selection
        uiConfig:
          type: string # JSON formatted
          description: Serialized plugin-specific UI configuration for the criteria
        tags:
          description: Unstructured key-value tags for the criteria
          type: object
          additionalProperties:
            type: string
            nullable: true
      required:
        - id
        - displayName
        - pluginName
        - selectionData
        - uiConfig
        - tags

    StudyCreateInfo:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for this study
        displayName:
          type: string
          description: Human readable name of the study

    Study:
      type: object
      required: [ id, created, createdBy, lastModified ]
      properties:
        id:
          description: ID of the study, immutable
          type: string
        displayName:
          type: string
          description: Human readable name of the study
        created:
          type: string
          format: date-time
        createdBy:
          description: Email of user who created the study
          type: string
        lastModified:
          type: string
          format: date-time

    ExportPreviewRequest:
      type: object
      properties:
        study:
          type: string
        cohorts:
          description: List of cohort ids
          type: array
          items:
            type: string
        featureSets:
          description: List of feature set ids
          type: array
          items:
            type: string
        limit:
          type: integer
        includeAllAttributes:
          type: boolean
          description: |
            When true, ignore the selected attributes in the data feature set definitions and include all
            attributes for each output entity.
          default: false
      required:
        - study
        - cohorts
        - featureSets

    EntityOutputPreview:
      type: object
      properties:
        entity:
          description: Entity name
          type: string
        includedAttributes:
          type: array
          description: Names of attributes included in the output
          items:
            type: string
        criteria:
          type: array
          items:
            type: object
            properties:
              conceptSetId:
                type: string
              criteriaId:
                type: string
            required:
              - conceptSetId
              - criteriaId
        indexSql:
          type: string
          description: |
            SQL string against the index tables.
            This will be populated if source queries are not configured for this entity.
        sourceSql:
          type: string
          description: |
            SQL string against the index tables.
            This will be populated if source queries are configured for this entity.
      required:
        - entity
        - includedAttributes
        - criteria

    EntityOutputPreviewList:
      type: object
      properties:
        entityOutputs:
          type: array
          items:
            $ref: "#/components/schemas/EntityOutputPreview"
      required:
        - entityOutputs
        
    ErrorReport:
      type: object
      required: [message, statusCode, causes]
      properties:
        message:
          type: string
        statusCode:
          type: integer
        causes:
          type: array
          items:
            type: string
          
  responses:
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorReport"

security:
  - oauth: []
