/* Note -- this is general script and these vars get envsubst in scripts.
 * CDR_DB_NAME , WORKBENCH_DB_USER AND PASSWORD,  may be substituted in scripts for PUBLIC versions,  .. etc
 * if creating a a differnt db with this script
 */
CREATE DATABASE IF NOT EXISTS ${CDR_DB_NAME} CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS '${WORKBENCH_DB_USER}'@'%' IDENTIFIED BY '${WORKBENCH_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${LIQUIBASE_DB_USER}'@'%' IDENTIFIED BY '${LIQUIBASE_DB_PASSWORD}';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON ${CDR_DB_NAME}.* TO '${WORKBENCH_DB_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, INDEX, REFERENCES, CREATE TEMPORARY TABLES, CREATE VIEW ON ${CDR_DB_NAME}.* TO '${LIQUIBASE_DB_USER}'@'%';
