#!/usr/bin/env bash

{ which git-secrets; } || {
  echo 'git-secrets required and not found. See README for installation instructions.'
  echo
  exit 1
}

{
  git config --remove-section secrets 2>/dev/null
} || {
  :
}
git secrets --add 'private_key'
git secrets --add 'private_key_id'
git secrets --add --allowed --literal "git secrets --add 'private_key'"
git secrets --add --allowed --literal "git secrets --add 'private_key_id'"

git secrets --pre_commit_hook -- "$@"

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
if [ "$CURRENT_BRANCH" = "master" ]
then
  echo Current branch is master, aborting commit.
  echo Please commit to a working branch and push it to GitHub for review/merge.
  exit 1
fi
