#!/usr/bin/env bash
{
  git config --remove-section secrets 2>/dev/null
} || {
  :
}
git secrets --add 'private_key'
git secrets --add 'private_key_id'
git secrets --add --allowed --literal "git secrets --add 'private_key'"
git secrets --add --allowed --literal "git secrets --add 'private_key_id'"

git secrets --prepare_commit_msg_hook -- "$@"
