CREATE SCHEMA IF NOT EXISTS ${TANAGRA_DB_NAME} CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT SELECT, INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, INDEX, REFERENCES, CREATE TEMPORARY TABLES, CREATE VIEW ON ${TANAGRA_DB_NAME}.* TO '${TANAGRA_DB_USERNAME}'@'%';
