import * as fp from 'lodash/fp';
import {formatUsd} from './numbers';

// Copied from https://github.com/DataBiosphere/terra-ui/blob/219b063b07d56499ccc38013fd88f4f0b88f8cd6/src/data/machines.js

export enum ComputeType {
  Standard = 'Standard VM',
  Dataproc = 'Dataproc Cluster'
}

export enum gpuTypes {
  NVDIATeslaT4 = 'nvidia-tesla-t4',
  NVDIATeslaV100 = 'nvidia-tesla-v100',
  NVDIATeslaK80 = 'nvidia-tesla-k80',
  NVDIATeslaP4 = 'nvidia-tesla-p4',
}

export const AutopauseMinuteThresholds = new Map([
  [30, '30 minutes (default)'],
  [60 * 8, '8 hours'],
  [5 * 24 * 60, '5 days'],
  [10 * 24 * 60, '10 days']
]);

export const DEFAULT_AUTOPAUSE_THRESHOLD_MINUTES = 30;

export interface Machine {
  name: string;
  cpu: number;
  memory: number;
  price: number;
  preemptiblePrice: number;
}

const machineBases: Machine[] = [
  { name: 'n1-standard-1', cpu: 1, memory: 3.75, price: 0.0475, preemptiblePrice: 0.0100 },
  { name: 'n1-standard-2', cpu: 2, memory: 7.50, price: 0.0950, preemptiblePrice: 0.0200 },
  { name: 'n1-standard-4', cpu: 4, memory: 15, price: 0.1900, preemptiblePrice: 0.0400 },
  { name: 'n1-standard-8', cpu: 8, memory: 30, price: 0.3800, preemptiblePrice: 0.0800 },
  { name: 'n1-standard-16', cpu: 16, memory: 60, price: 0.7600, preemptiblePrice: 0.1600 },
  { name: 'n1-standard-32', cpu: 32, memory: 120, price: 1.5200, preemptiblePrice: 0.3200 },
  { name: 'n1-standard-64', cpu: 64, memory: 240, price: 3.0400, preemptiblePrice: 0.6400 },
  { name: 'n1-standard-96', cpu: 96, memory: 360, price: 4.5600, preemptiblePrice: 0.9600 },
  { name: 'n1-highmem-2', cpu: 2, memory: 13, price: 0.1184, preemptiblePrice: 0.0250 },
  { name: 'n1-highmem-4', cpu: 4, memory: 26, price: 0.2368, preemptiblePrice: 0.0500 },
  { name: 'n1-highmem-8', cpu: 8, memory: 52, price: 0.4736, preemptiblePrice: 0.1000 },
  { name: 'n1-highmem-16', cpu: 16, memory: 104, price: 0.9472, preemptiblePrice: 0.2000 },
  { name: 'n1-highmem-32', cpu: 32, memory: 208, price: 1.8944, preemptiblePrice: 0.4000 },
  { name: 'n1-highmem-64', cpu: 64, memory: 416, price: 3.7888, preemptiblePrice: 0.8000 },
  { name: 'n1-highmem-96', cpu: 96, memory: 624, price: 5.6832, preemptiblePrice: 1.2000 },
  { name: 'n1-highcpu-2', cpu: 2, memory: 1.8, price: 0.0709, preemptiblePrice: 0.0150 },
  { name: 'n1-highcpu-4', cpu: 4, memory: 3.6, price: 0.1418, preemptiblePrice: 0.0300 },
  { name: 'n1-highcpu-8', cpu: 8, memory: 7.2, price: 0.2836, preemptiblePrice: 0.0600 },
  { name: 'n1-highcpu-16', cpu: 16, memory: 14.4, price: 0.5672, preemptiblePrice: 0.1200 },
  { name: 'n1-highcpu-32', cpu: 32, memory: 28.8, price: 1.1344, preemptiblePrice: 0.2400 },
  { name: 'n1-highcpu-64', cpu: 64, memory: 57.6, price: 2.2688, preemptiblePrice: 0.4800 },
  { name: 'n1-highcpu-96', cpu: 96, memory: 86.4, price: 3.402, preemptiblePrice: 0.7200 }
];

export interface Gpu {
  machineName: string;
  gpuType: gpuTypes;
  gpuNum: number;
  gpuPrice: number;
}

export const gpuBases: Gpu[] = [
    // GPU available configurations generated by script. See the original table in https://support.terra.bio/hc/en-us/articles/4403006001947
    // NVIDIA Tesla T4 Configuration
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 1, gpuPrice: 0.41},
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 0.76},
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 1.46},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 1, gpuPrice: 0.45},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 0.80},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 1.50},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 1, gpuPrice: 0.48},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 0.83},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 1.53},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 1, gpuPrice: 0.55},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 0.90},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 1.60},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 1, gpuPrice: 0.60},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 0.95},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 1.65},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 1, gpuPrice: 0.64},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 0.99},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 1.69},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 1, gpuPrice: 0.74},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 1.09},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 1.79},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 1, gpuPrice: 0.83},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 1.18},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 1.88},
  { machineName: 'n1-highcpu-16', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 1, gpuPrice: 0.93},
  { machineName: 'n1-highcpu-16', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 1.28},
  { machineName: 'n1-highcpu-16', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 1.98},
  { machineName: 'n1-standard-16', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 1, gpuPrice: 1.12},
  { machineName: 'n1-standard-16', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 1.47},
  { machineName: 'n1-standard-16', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 2.17},
  { machineName: 'n1-highmem-16', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 1, gpuPrice: 1.31},
  { machineName: 'n1-highmem-16', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 1.66},
  { machineName: 'n1-highmem-16', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 2.36},
  { machineName: 'n1-highcpu-32', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 1.84},
  { machineName: 'n1-highcpu-32', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 2.54},
  { machineName: 'n1-standard-32', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 2.23},
  { machineName: 'n1-standard-32', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 2.93},
  { machineName: 'n1-highmem-32', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 2, gpuPrice: 2.60},
  { machineName: 'n1-highmem-32', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 3.30},
  { machineName: 'n1-highcpu-64', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 3.68},
  { machineName: 'n1-standard-64', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 4.45},
  { machineName: 'n1-highmem-64', gpuType: gpuTypes.NVDIATeslaT4, gpuNum: 4, gpuPrice: 5.20},
  // NVIDIA Tesla K80 Configuration
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 1, gpuPrice: 0.51},
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 2, gpuPrice: 0.96},
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 1.41},
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 1.86},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 1, gpuPrice: 0.55},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 2, gpuPrice: 1.00},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 1.46},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 1.90},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 1, gpuPrice: 0.58},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 2, gpuPrice: 1.03},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 1.48},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 1.93},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 1, gpuPrice: 0.65},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 2, gpuPrice: 1.10},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 1.55},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 2.00},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 1, gpuPrice: 0.70},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 2, gpuPrice: 1.15},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 1.60},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 2.05},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 1, gpuPrice: 0.74},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 2, gpuPrice: 1.19},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 1.64},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 2.09},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 1, gpuPrice: 0.84},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 2, gpuPrice: 1.29},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 1.74},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 2.19},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 1, gpuPrice: 0.93},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 2, gpuPrice: 1.38},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 1.83},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 2.28},
  { machineName: 'n1-highcpu-16', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 2, gpuPrice: 1.48},
  { machineName: 'n1-highcpu-16', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 1.93},
  { machineName: 'n1-highcpu-16', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 2.38},
  { machineName: 'n1-standard-16', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 2, gpuPrice: 1.67},
  { machineName: 'n1-standard-16', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 2.12},
  { machineName: 'n1-standard-16', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 2.57},
  { machineName: 'n1-highmem-16', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 2, gpuPrice: 1.86},
  { machineName: 'n1-highmem-16', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 2.31},
  { machineName: 'n1-highmem-16', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 2.76},
  { machineName: 'n1-highcpu-32', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 2.49},
  { machineName: 'n1-highcpu-32', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 2.94},
  { machineName: 'n1-standard-32', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 2.88},
  { machineName: 'n1-standard-32', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 3.33},
  { machineName: 'n1-highmem-32', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 4, gpuPrice: 3.25},
  { machineName: 'n1-highmem-32', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 3.70},
  { machineName: 'n1-highcpu-64', gpuType: gpuTypes.NVDIATeslaK80, gpuNum: 8, gpuPrice: 4.08 / 3.63},
  // NVIDIA Tesla P4 Configuration
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 1, gpuPrice: 0.66},
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 1.26},
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 1.86},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 1, gpuPrice: 0.70},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 1.30},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 1.90},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 1, gpuPrice: 0.73},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 1.33},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 1.93},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 1, gpuPrice: 0.80},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 1.40},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 2.00},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 1, gpuPrice: 0.85},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 1.45},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 2.05},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 1, gpuPrice: 0.89},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 1.49},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 2.09},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 1, gpuPrice: 0.99},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 1.59},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 2.19},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 1, gpuPrice: 1.08},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 1.68},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 2.28},
  { machineName: 'n1-highcpu-16', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 1, gpuPrice: 1.18},
  { machineName: 'n1-highcpu-16', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 1.78},
  { machineName: 'n1-highcpu-16', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 2.38},
  { machineName: 'n1-standard-16', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 1, gpuPrice: 1.37},
  { machineName: 'n1-standard-16', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 1.97},
  { machineName: 'n1-standard-16', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 2.57},
  { machineName: 'n1-highmem-16', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 1, gpuPrice: 1.56},
  { machineName: 'n1-highmem-16', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 2.16},
  { machineName: 'n1-highmem-16', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 2.76},
  { machineName: 'n1-highcpu-32', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 2.34},
  { machineName: 'n1-highcpu-32', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 2.94},
  { machineName: 'n1-standard-32', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 2.73},
  { machineName: 'n1-standard-32', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 3.33},
  { machineName: 'n1-highmem-32', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 2, gpuPrice: 3.10},
  { machineName: 'n1-highmem-32', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 3.70},
  { machineName: 'n1-highcpu-64', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 4.08},
  { machineName: 'n1-standard-64', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 4.85},
  { machineName: 'n1-highmem-64', gpuType: gpuTypes.NVDIATeslaP4, gpuNum: 4, gpuPrice: 5.60},
  // NVIDIA Tesla V100 Configuration
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 1, gpuPrice: 2.54},
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 2, gpuPrice: 5.02},
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 9.98},
  { machineName: 'n1-standard-1', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 19.90},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 1, gpuPrice: 2.58},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 2, gpuPrice: 5.06},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 10.02},
  { machineName: 'n1-standard-2', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 19.94},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 1, gpuPrice: 2.61},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 2, gpuPrice: 5.09},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 10.05},
  { machineName: 'n1-highmem-2', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 19.97},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 1, gpuPrice: 2.68},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 2, gpuPrice: 5.16},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 10.12},
  { machineName: 'n1-standard-4', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 20.04},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 1, gpuPrice: 2.73},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 2, gpuPrice: 5.21},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 10.17},
  { machineName: 'n1-highmem-4', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 20.09},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 1, gpuPrice: 2.77},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 2, gpuPrice: 5.25},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 10.21},
  { machineName: 'n1-highcpu-8', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 20.13},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 1, gpuPrice: 2.87},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 2, gpuPrice: 5.35},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 10.31},
  { machineName: 'n1-standard-8', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 20.23},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 1, gpuPrice: 2.96},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 2, gpuPrice: 5.44},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 10.40},
  { machineName: 'n1-highmem-8', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 20.32},
  { machineName: 'n1-highcpu-16', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 2, gpuPrice: 5.54},
  { machineName: 'n1-highcpu-16', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 10.50},
  { machineName: 'n1-highcpu-16', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 20.42},
  { machineName: 'n1-standard-16', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 2, gpuPrice: 5.73},
  { machineName: 'n1-standard-16', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 10.69},
  { machineName: 'n1-standard-16', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 20.61},
  { machineName: 'n1-highmem-16', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 2, gpuPrice: 5.92},
  { machineName: 'n1-highmem-16', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 10.88},
  { machineName: 'n1-highmem-16', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 20.80},
  { machineName: 'n1-highcpu-32', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 11.06},
  { machineName: 'n1-highcpu-32', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 20.98},
  { machineName: 'n1-standard-32', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 11.45},
  { machineName: 'n1-standard-32', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 21.37},
  { machineName: 'n1-highmem-32', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 4, gpuPrice: 11.82},
  { machineName: 'n1-highmem-32', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 21.74},
  { machineName: 'n1-highcpu-64', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 22.12},
  { machineName: 'n1-standard-64', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 22.89},
  { machineName: 'n1-highmem-64', gpuType: gpuTypes.NVDIATeslaV100, gpuNum: 8, gpuPrice: 23.64},
];

export const allMachineTypes: Machine[] = fp.map(({ price, preemptiblePrice, ...details }) => ({
  price: price + 0.004,
  preemptiblePrice: preemptiblePrice + 0.002,
  ...details
}), machineBases); // adding prices for ephemeral IP's, per https://cloud.google.com/compute/network-pricing#ipaddress

// Initial price restriction to limit against larger machines being used with free tier.
// This can be reevaluated later, if researchers really want to use very large machines
// with their own billing accounts.
const maxMachinePrice = 1.6;

// Following constraints follow findings on RW-5763, last tested 11/19/20. Using
// machine types below this limit results in either an immediate ERROR status,
// or a delayed ERROR status after the runtime times out in the CREATING state.
// See also https://broadworkbench.atlassian.net/browse/SATURN-1337, where the
// determination was made for Dataproc master machines only.
const validPricedTypes = allMachineTypes.filter(({price}) => price < maxMachinePrice);
export const validLeoGceMachineTypes = validPricedTypes.filter(({memory}) => memory >= 2);
export const validLeoDataprocMasterMachineTypes = validPricedTypes.filter(({memory}) => memory > 4);
export const validLeoDataprocWorkerMachineTypes = validPricedTypes.filter(({memory}) => memory >= 3);

export const findMachineByName = (machineToFind: string) => fp.find(({name}) => name === machineToFind, allMachineTypes);
export const findGpu = (machineToFind: string, type: string, num: number) =>
    fp.find(({machineName, gpuType, gpuNum}) => machineName === machineToFind && gpuType === type && gpuNum === num, gpuBases);

export const diskPrice = 0.04 / 730; // per GB hour, from https://cloud.google.com/compute/pricing
export const dataprocCpuPrice = 0.01; // dataproc costs $0.01 per cpu per hour

const dataprocSurcharge = ({masterMachine, numberOfWorkers, numberOfPreemptibleWorkers, workerMachine}) => {
  const costs = [masterMachine.cpu * dataprocCpuPrice];
  if (workerMachine && numberOfWorkers) {
    costs.push(numberOfWorkers * workerMachine.cpu * dataprocCpuPrice);
  }
  if (workerMachine && numberOfPreemptibleWorkers) {
    costs.push(numberOfPreemptibleWorkers * workerMachine.cpu * dataprocCpuPrice);
  }
  return fp.sum(costs);
};

// The following calculations were based off of Terra UI's cost estimator:
// https://github.com/DataBiosphere/terra-ui/blob/cf5ec4408db3bd1fcdbcc5302da62d42e4d03ca3/src/components/ClusterManager.js#L85

export const machineStorageCost = ({
    masterDiskSize,
    numberOfPreemptibleWorkers,
    numberOfWorkers,
    workerDiskSize
}) => {
  return fp.sum([
    masterDiskSize * diskPrice,
    numberOfWorkers ? numberOfWorkers * workerDiskSize * diskPrice : 0,
    numberOfPreemptibleWorkers ? numberOfPreemptibleWorkers * workerDiskSize * diskPrice : 0
  ]);
};

export const machineStorageCostBreakdown = ({
    masterDiskSize,
    numberOfPreemptibleWorkers,
    numberOfWorkers,
    workerDiskSize
}) => {
  const costs = [];
  if (workerDiskSize) {
    costs.push(`${formatUsd(masterDiskSize * diskPrice)}/hr Master Disk`);
    if (numberOfWorkers) {
      costs.push(`${formatUsd((numberOfWorkers * workerDiskSize) * diskPrice)}/hr Worker Disk(s)`);
    }
    if (numberOfPreemptibleWorkers) {
      costs.push(`${formatUsd((numberOfPreemptibleWorkers * workerDiskSize) * diskPrice)}/hr Preemptible Worker Disk(s)`);
    }
  } else {
    costs.push(`${formatUsd(masterDiskSize * diskPrice)}/hr Disk`);
  }
  return costs;
};

export const machineRunningCost = ({
  computeType,
  masterDiskSize,
  masterMachine,
  gpu,
  numberOfWorkers = 0,
  numberOfPreemptibleWorkers = 0,
  workerDiskSize,
  workerMachine
}) => {
  const dataprocPrice = computeType === ComputeType.Dataproc
    ? fp.sum([
      dataprocSurcharge({
        masterMachine: masterMachine,
        numberOfWorkers: numberOfWorkers,
        numberOfPreemptibleWorkers: numberOfPreemptibleWorkers,
        workerMachine: workerMachine
      }),
      workerMachine
          ? fp.sum([
            numberOfWorkers * workerMachine.price,
            numberOfPreemptibleWorkers * workerMachine.preemptiblePrice
          ])
          : 0
    ])
    : 0;
  return fp.sum([
    dataprocPrice,
    masterMachine.price,
    gpu ? gpu.gpuPrice : 0,
    machineStorageCost({
      masterDiskSize: masterDiskSize,
      numberOfPreemptibleWorkers: numberOfPreemptibleWorkers,
      numberOfWorkers: numberOfWorkers,
      workerDiskSize: workerDiskSize
    })
  ]);
};

export const machineRunningCostBreakdown = ({
  computeType,
  masterDiskSize,
  masterMachine,
    gpu,
  numberOfWorkers = 0,
  numberOfPreemptibleWorkers = 0,
  workerDiskSize,
  workerMachine
}) => {
  const costs = [];
  if (computeType === ComputeType.Dataproc) {
    if (workerMachine) {
      costs.push(`${formatUsd(masterMachine.price)}/hr Master VM`);
      if (numberOfWorkers > 0) {
        costs.push(`${formatUsd(workerMachine.price  * numberOfWorkers)}/hr Worker VM(s) (${numberOfWorkers})`);
      }
      if (numberOfPreemptibleWorkers > 0) {
        costs.push(
          `${formatUsd(workerMachine.preemptiblePrice * numberOfPreemptibleWorkers)}/hr Preemptible Worker VM(s) ` +
          `(${numberOfPreemptibleWorkers})`
        );
      }
    }
    const dataprocSurchargeAmount = dataprocSurcharge({
      masterMachine: masterMachine,
      numberOfWorkers: numberOfWorkers,
      numberOfPreemptibleWorkers: numberOfPreemptibleWorkers,
      workerMachine: workerMachine
    });
    costs.push(`${formatUsd(dataprocSurchargeAmount)}/hr Dataproc Per-CPU Surcharge`);
  } else {
    costs.push(`${formatUsd(masterMachine.price)}/hr VM`);
    if (!!gpu) {
      costs.push(`${formatUsd(gpu.gpuPrice)}/hr GPU`);
    }
  }
  costs.push(
    ...machineStorageCostBreakdown({
      masterDiskSize: masterDiskSize,
      numberOfPreemptibleWorkers: numberOfPreemptibleWorkers,
      numberOfWorkers: numberOfWorkers,
      workerDiskSize: workerDiskSize
    })
  );
  return costs;
};
