-- This file is being used by ApplicationTest.java to load application configuration at initialization time.
insert into config (config_id, configuration) values
  ('main', '{"firecloud":{"baseUrl":"https://firecloud-orchestration.dsde-dev.broadinstitute.org","billingAccountId":"014D91-FCB792-33D2C0","billingProjectPrefix":"aou-rw-local1-","clusterMaxAgeDays":7,"clusterIdleMaxAgeDays":3,"debugEndpoints":false,"leoBaseUrl":"https://leonardo.dsde-dev.broadinstitute.org","registeredDomainName":"all-of-us-registered-test","billingRetryCount":2},"auth":{"serviceAccountApiUsers":["all-of-us-workbench-test@appspot.gserviceaccount.com"]},"cdr":{"debugQueries":false},"googleCloudStorageService":{"credentialsBucketName":"all-of-us-workbench-test-credentials","emailImagesBucketName":"all-of-us-workbench-test-email-images","clusterResourcesBucketName":"gs://all-of-us-workbench-test-cluster-resources"},"googleDirectoryService":{"gSuiteDomain":"fake-research-aou.org"},"server":{"apiBaseUrl":"https://api-dot-all-of-us-workbench-test.appspot.com","publicApiKeyForErrorReports":"","projectId":"all-of-us-workbench-test","shortName":"Local","oauthClientId":"602460048110-5uk3vds3igc9qo0luevroc2uc3okgbkt.apps.googleusercontent.com"},"admin":{"loginUrl":"http://localhost:4200/login","adminIdVerification":"manual-id-verification-requests@fake-research-aou.org"},"mandrill":{"fromEmail":"donotreply@fake-research-aou.org","sendRetries":3},"elasticsearch":{"host":"localhost:9200","enableElasticsearchBackend":true}}');

insert into config (config_id, configuration) values
  ('cdrBigQuerySchema', '{"description":"Configuration specifying the schema for tables in the CDR, including foreign key relationships. Adapted from BigQuery schema files"}');

insert into cdr_version(cdr_version_id, is_default, name, data_access_level, release_number, bigquery_project, bigquery_dataset, creation_time, num_participants, cdr_db_name, elastic_index_base_name, public_db_name) VALUES
  (1, 1, 'Test Registered CDR', 1, 1, 'all-of-us-ehr-dev', 'synthetic_cdr20180606', SYSDATE(), 942637, 'cdr20180223', 'cdr20180223', 'public20180223');
