runtime: nodejs18
default_expiration: "2m"

handlers:
- url: /(.*\.(css|eot|gz|html|ico|jpg|jpeg|js|map|mp4|pdf|png|svg|ttf|woff|woff2))
  static_files: build/\1
  upload: build/(.*)
  secure: always
  http_headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-XSS-Protection: 1
    X-Content-Type-Options: "nosniff"
    Content-Security-Policy: "default-src 'none'; img-src 'self'; style-src 'unsafe-inline'; frame-ancestors 'self'; report-uri /content-security-report"
- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always
  http_headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-XSS-Protection: 1
    X-Content-Type-Options: "nosniff"
    # This can be removed once the below Content-Security-Policy is enforced, it
    # is obsoleted by frame-ancestors.
    X-Frame-Options: SAMEORIGIN
    # unsafe-inline is unfortunately required as the Incapsula WAF injects a
    # script onto the page when we're serving in production, for which we'd be
    # unable to precompute a hash.
    Content-Security-Policy-Report-Only: "
      default-src 'none';
      script-src
        'self'
        'unsafe-inline'
        https://apis.google.com
        https://*.googleapis.com
        https://static.zdassets.com
        https://www.googletagmanager.com
        https://www.google-analytics.com;
      style-src
        'self'
        'unsafe-inline'
        https://fonts.googleapis.com;
      img-src
        'self'
        data:
        https://*.googleusercontent.com
        https://www.google-analytics.com;
      font-src
        'self'
        data:
        https://fonts.gstatic.com;
      connect-src
        'self'
        https://api-dot-all-of-us-workbench-test.appspot.com
        https://api.test.fake-research-aou.org
        https://api-dot-all-of-us-rw-staging.appspot.com
        https://api.staging.fake-research-aou.org
        https://api.stable.fake-research-aou.org
        https://api.preprod-workbench.researchallofus.org
        https://api.workbench.researchallofus.org
        https://leonardo.dsde-dev.broadinstitute.org
        https://notebooks.firecloud.org
        https://firecloud-orchestration.dsde-dev.broadinstitute.org
        https://api.firecloud.org
        https://*.googleapis.com
        https://*.zdassets.com
        https://aousupporthelp.zendesk.com
        https://aousupporthelp1634849601.zendesk.com
        https://www.google-analytics.com
        https://test.fake-research-aou.org;
      child-src
        'self'
        https://accounts.google.com
        https://leonardo.dsde-dev.broadinstitute.org
        https://notebooks.firecloud.org;
      report-uri /content-security-index-report"
