version: "3.4"

# x- indicates an "extension", so docker-compose will ignore the attribute. The
# name is not important, it's just the necessary syntax to create a YAML anchor
# for reuse across the below services.
x-api-defaults: &api-defaults
  # This image label exists for documentation purposes only, e.g. to identify
  # it via `docker images`. We do not actually push this image up to DockerHub.
  # Since docker-compose should never find this image remotely, it will rebuild
  # it from the provided build context or use a cached local version.
  # When making changes to this image, you can modify this tag to force all devs
  # to rebuild.
  image: allofustest/workbench-dev-api:local-6
  build:
    context: ./src/dev/server
  user: ${UID}
  working_dir: /w/api
  env_file:
    - db/vars.env

services:
  db:
    image: mysql:5.7.27
    env_file:
      - db/vars.env
    volumes:
      - db:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
  db-cloudsql-import:
    <<: *api-defaults
    working_dir: /w/api/db-cdr
    entrypoint: ["./generate-cdr/cloudsql-import.sh"]

  db-local-mysql-import:
    <<: *api-defaults
    working_dir: /w/api/db-cdr
    entrypoint: ["./generate-cdr/local-mysql-import.sh"]

volumes:
  db:
